# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VK_SolovievaIrina' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.8.1'
  pod 'SwiftyJSON', '~> 4.2.0'
  pod 'Kingfisher', '~> 5.1.0'
  pod 'RealmSwift'

  # Pods for VK_SolovievaIrina

  target 'VK_SolovievaIrinaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VK_SolovievaIrinaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
